#!/bin/sh
#
# Hook that make sure the right email is used for my repositories
#

# Redirect output to stderr.
exec 1>&2

enterprise_email='Henri.Tremblay@pj.ca'

remote_url="$(git config --get remote.origin.url)"

if [[ "$remote_url" == '' ]]
then
  echo "ERROR: Please set the origin url"
  exit 1
fi

email="$(git config --get user.email)"
echo "Committing with $email"

if [[ $remote_url == *"ypg.com"* ]]
then
  if [[ $email != $enterprise_email ]]
  then
    git config user.email $enterprise_email
    echo "ERROR: Setting email to $enterprise_email, please redo your commit"
    exit 1
  fi
elif [[ $email == $enterprise_email ]]
then
  echo "ERROR: Using YP email for an external account!"
  exit 1
fi
